// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tnM4fJ4V3QSWAt6aqkZcfw
// Component: gY1sAZRLnE17A
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import NmMenu from "../../NmMenu"; // plasmic-import: B4PSLPMggBQC/component
import NmProductTitleAndStars from "../../NmProductTitleAndStars"; // plasmic-import: hs4EtlOe_iskB/component
import NmProductDescription from "../../NmProductDescription"; // plasmic-import: q-7jyH5zxIpxa/component
import NmImageCarouselShim from "../../NmImageCarouselShim"; // plasmic-import: AHDP_gGUT0_Z/component
import NmVariantSelectionButton from "../../NmVariantSelectionButton"; // plasmic-import: -1PcR9_co3L6d/component
import "@plasmicapp/react-web/lib/plasmic.css";
import defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import projectcss from "./plasmic_copy_of_nm.module.css"; // plasmic-import: tnM4fJ4V3QSWAt6aqkZcfw/projectcss
import sty from "./PlasmicShopNow.module.css"; // plasmic-import: gY1sAZRLnE17A/css

export const PlasmicShopNow__VariantProps = new Array();

export const PlasmicShopNow__ArgProps = new Array();

function PlasmicShopNow__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        className={classNames(defaultcss.all, sty.box)}
      >
        <NmMenu
          data-plasmic-name={"nmMenu"}
          data-plasmic-override={overrides.nmMenu}
          className={classNames("__wab_instance", sty.nmMenu)}
        />

        <NmProductTitleAndStars
          data-plasmic-name={"nmProductTitleAndStars"}
          data-plasmic-override={overrides.nmProductTitleAndStars}
          className={classNames("__wab_instance", sty.nmProductTitleAndStars)}
        />

        <NmProductDescription
          data-plasmic-name={"nmProductDescription"}
          data-plasmic-override={overrides.nmProductDescription}
          className={classNames("__wab_instance", sty.nmProductDescription)}
        />

        <NmImageCarouselShim
          data-plasmic-name={"nmImageCarouselShim"}
          data-plasmic-override={overrides.nmImageCarouselShim}
          className={classNames("__wab_instance", sty.nmImageCarouselShim)}
        />
      </div>

      <NmVariantSelectionButton
        data-plasmic-name={"nmVariantSelectionButton"}
        data-plasmic-override={overrides.nmVariantSelectionButton}
        className={classNames("__wab_instance", sty.nmVariantSelectionButton)}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "box",
    "nmMenu",
    "nmProductTitleAndStars",
    "nmProductDescription",
    "nmImageCarouselShim",
    "nmVariantSelectionButton"
  ],

  box: [
    "box",
    "nmMenu",
    "nmProductTitleAndStars",
    "nmProductDescription",
    "nmImageCarouselShim"
  ],

  nmMenu: ["nmMenu"],
  nmProductTitleAndStars: ["nmProductTitleAndStars"],
  nmProductDescription: ["nmProductDescription"],
  nmImageCarouselShim: ["nmImageCarouselShim"],
  nmVariantSelectionButton: ["nmVariantSelectionButton"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicShopNow__ArgProps,
      internalVariantPropNames: PlasmicShopNow__VariantProps
    });

    return PlasmicShopNow__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicShopNow";
  } else {
    func.displayName = `PlasmicShopNow.${nodeName}`;
  }
  return func;
}

export const PlasmicShopNow = Object.assign(
  // Top-level PlasmicShopNow renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),
    nmMenu: makeNodeComponent("nmMenu"),
    nmProductTitleAndStars: makeNodeComponent("nmProductTitleAndStars"),
    nmProductDescription: makeNodeComponent("nmProductDescription"),
    nmImageCarouselShim: makeNodeComponent("nmImageCarouselShim"),
    nmVariantSelectionButton: makeNodeComponent("nmVariantSelectionButton"),
    // Metadata about props expected for PlasmicShopNow
    internalVariantProps: PlasmicShopNow__VariantProps,
    internalArgProps: PlasmicShopNow__ArgProps
  }
);

export default PlasmicShopNow;
/* prettier-ignore-end */
