// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tnM4fJ4V3QSWAt6aqkZcfw
// Component: B4PSLPMggBQC
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import projectcss from "./plasmic_copy_of_nm.module.css"; // plasmic-import: tnM4fJ4V3QSWAt6aqkZcfw/projectcss
import sty from "./PlasmicNmMenu.module.css"; // plasmic-import: B4PSLPMggBQC/css
import Star24PxsvgIcon from "./icons/PlasmicIcon__Star24Pxsvg"; // plasmic-import: 6d3gmgPb3EiUf/icon

export const PlasmicNmMenu__VariantProps = new Array();

export const PlasmicNmMenu__ArgProps = new Array();

function PlasmicNmMenu__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"columns"}
        data-plasmic-override={overrides.columns}
        className={classNames(defaultcss.all, sty.columns)}
      >
        <div
          data-plasmic-name={"column"}
          data-plasmic-override={overrides.column}
          className={classNames(defaultcss.all, sty.column)}
        >
          <div className={classNames(defaultcss.all, sty.box__c7Iv)}>
            <Star24PxsvgIcon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(defaultcss.all, sty.svg)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__bcHrn
              )}
            >
              {"Logo"}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "columns", "column", "svg"],
  columns: ["columns", "column", "svg"],
  column: ["column", "svg"],
  svg: ["svg"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNmMenu__ArgProps,
      internalVariantPropNames: PlasmicNmMenu__VariantProps
    });

    return PlasmicNmMenu__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNmMenu";
  } else {
    func.displayName = `PlasmicNmMenu.${nodeName}`;
  }
  return func;
}

export const PlasmicNmMenu = Object.assign(
  // Top-level PlasmicNmMenu renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    columns: makeNodeComponent("columns"),
    column: makeNodeComponent("column"),
    svg: makeNodeComponent("svg"),
    // Metadata about props expected for PlasmicNmMenu
    internalVariantProps: PlasmicNmMenu__VariantProps,
    internalArgProps: PlasmicNmMenu__ArgProps
  }
);

export default PlasmicNmMenu;
/* prettier-ignore-end */
