// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tnM4fJ4V3QSWAt6aqkZcfw
// Component: AHDP_gGUT0_Z
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import projectcss from "./plasmic_copy_of_nm.module.css"; // plasmic-import: tnM4fJ4V3QSWAt6aqkZcfw/projectcss
import sty from "./PlasmicNmImageCarouselShim.module.css"; // plasmic-import: AHDP_gGUT0_Z/css

export const PlasmicNmImageCarouselShim__VariantProps = new Array();

export const PlasmicNmImageCarouselShim__ArgProps = new Array();

function PlasmicNmImageCarouselShim__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNmImageCarouselShim__ArgProps,
      internalVariantPropNames: PlasmicNmImageCarouselShim__VariantProps
    });

    return PlasmicNmImageCarouselShim__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNmImageCarouselShim";
  } else {
    func.displayName = `PlasmicNmImageCarouselShim.${nodeName}`;
  }
  return func;
}

export const PlasmicNmImageCarouselShim = Object.assign(
  // Top-level PlasmicNmImageCarouselShim renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicNmImageCarouselShim
    internalVariantProps: PlasmicNmImageCarouselShim__VariantProps,
    internalArgProps: PlasmicNmImageCarouselShim__ArgProps
  }
);

export default PlasmicNmImageCarouselShim;
/* prettier-ignore-end */
